### PR TITLE
Swap entry url with origin url if graby provides an updated one

### LINKED ISSUE #3529: Added link is different than the original one
:warning: If your issue is about an error during fetching a link, please read: http://doc.wallabag.org/en/user/errors_during_fetching.html#how-can-i-help-to-fix-that

### Issue details

Content fetching alters the link user added thus the source address stored in reading list may end up being completely different than what did the user originally intended.

For example:
* Add https://www.reddit.com/r/linux/comments/7lgnho/llvm_501_release/ to Wallabag
* http://lists.llvm.org/pipermail/llvm-announce/2017-December/000076.html gets added instead

fetched content is content of the article posted to reddit (in other words not the comments page the user submitted to Wallabag). This may or may not be the desirable outcome for fetched text but I don't want to discuss this as this is not the real issue here.

I think the real issue here is that the original link the user has submitted is lost, even if the user clicks the original link he'll go to the content page instead of reddit discussion page.

I checked that link in https://f43.me/feed/test and the result is same. I don't know if this is the intended behavior of the fetcher or a bug, but I think it is another issue which should not distract from this one. 

I think that the original link submitted by the user should not be changed under any circumstances regardless of what result comes from fetching.

Thanks

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.2.3
* How did you install wallabag? Via `git clone` or by downloading the package? Package
* Last wallabag version that did not exhibit the issue (if applicable): not checked
* php version: 5.6.30
* OS: Debian 8.0
* type of hosting (shared or dedicated): Dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): SQLite

### Steps to reproduce/test case

provided above

### PR DESCRIPTION
**Pull request by Kdecherf**
| Q             | A
| ------------- | ---
| Bug fix?      | _sort of_
| New feature?  | _sort of_
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| Fixed tickets | #3529 
| License       | MIT

Fixes #3529 

This PR is a partial fix for #3529: it still set the final url as the actual entry url, but now it sets origin_url field to the former url.

Ex:
Current behavior:
- User saves a reddit.com to Wallabag
- Graby fetchs the page and finds a new link to follow (llvm.org)
- Entry is saved with llvm.org as the entry url

| Given url | Fetched url | Stored url | Stored origin url |
| - | - | - | - |
| `https://www.reddit.com/r/li[…]` | `http://lists.llvm.org/pip[…]` | `http://lists.llvm.org/pip[…]` | - |

New behavior:
- User saves a reddit.com to Wallabag
- Graby fetchs the page and finds a new link to follow (llvm.org)
- Entry is saved with llvm.org as the entry url and reddit.com as the origin url

| Given url | Given origin url | Fetched url | Stored url | Stored origin url | Diff |
| - | - | - | - | - | - |
| `https://www.reddit.com/r/li[…]` | - | `http://lists.llvm.org/pip[…]` | `http://lists.llvm.org/pip[…]` |  `https://www.reddit.com/r/li[…]` | url |
| `https://www.lemonde.fr/tiny[…]` | - | `https://www.lemonde.fr/m-deco[…]` | `https://www.lemonde.fr/m-deco[…]` | - | lemonde regex |
| `http://www.example.org/blah[…]` | - | `https://www.example.org/blah[…]` | `https://www.example.org/blah[…]` | - | scheme |
| `https://www.medium.com/hello[…]` | - | `https://www.medium.com/hello#world[…]` | `https://www.medium.com/hello[…]` | - | fragment
| `https://www.mylink.com/foo[…]` | `https://twitter.com[…]` | `https://www.anotherlink.com/bar[…]` | `https://www.anotherlink.com/bar[…]` | `https://twitter.com[…]` | origin url already set |
| `http://feedproxy.google.com/~r/Wa[…]` | - | `https://example.org/hello-wallabag[…]` | `https://example.org/hello-wallabag[…]` | - | host ignore list |

Here is the hardcoded ignore list for specific patterns : 
- `feedproxy.google.com`
- `feeds.reuters.com`
- `https?://www\.lemonde\.fr/tiny.*`

Todo
- [x] leave origin_url unchanged if difference is an ending slash
- [x] leave origin_url unchanged if difference is a fragment
- [x] leave origin_url unchanged if new value matches the ignore list

### CODE REVIEW

**Comment by Kdecherf** [comment]
Well, after using this PR for few days, there's a new behavior for which I don't know if it'll annoy users:

I fetch news using a rss feed reader and share articles that I'm interested in into wallabag (Android share).

Some RSS providers like Le Monde and Slashdot use dedicated rss links which redirects to the actual content.
Until now the initial link (rss.slashdot.org for slashdot, lemonde.fr/tiny for Le Monde) is not kept. But with this PR this former link is now visible, e.g.:

2018-01-13-150229_1920x1080

**Comment by Kdecherf** [comment]
New change: this PR does not override `origin_url` if it's not empty

**Comment by Kdecherf** [comment]
Hey there,

Regarding my last comment I think I will add a custom parameter (in `parameters.yml`) to ignore some domains like feedproxy.google.com, rss.slashdot.org. Toughts @wallabag/core?

**Comment by j0k3r** [comment]
Please, re-explain 🙂 
I've re-read you few last comments, and I don't get it.

**Comment by Kdecherf** [comment]
This PR fills empty `origin_url` with former url in case of redirection (`single_page_link` or HTTP redirection).

When you use a RSS reader and share articles to Wallabag, they often come from an intermediate url, e.g.:
- PetaPixel articles have feedproxy.google.com/~r/PetaPixel/ as former url
- LeMonde.fr articles have lemonde.fr/tiny as former url

Imo it's somewhat annoying and not very useful. That's why I suggest adding an ignore list in `parameters.yml` to prevent these links to be set as `origin_url`.

**Comment by j0k3r** [comment]
Can you rebase your branch against the master?

**Comment by Kdecherf** [comment]
I consider this PR ready for review. I'll update the PR message with a table to explain the different behaviors introduced with it.

File: src/Wallabag/CoreBundle/Helper/ContentProxy.php [hunk 1]
```diff
@@ -305,6 +312,90 @@ private function stockEntry(Entry $entry, array $content)
...
+            $diff_ce = array_diff_assoc($parsed_content_url, $parsed_entry_url);
+
+            $diff = array_merge($diff_ec, $diff_ce);
+            $diff_keys = array_keys($diff);
+            sort($diff_keys);
+
+            if ($this->ignoreUrl($entry->getUrl())) {
+                $entry->setUrl($url);
+            } else {
+                switch ($diff_keys) {
```
Comment (j0k3r) [inline src/Wallabag/CoreBundle/Helper/ContentProxy.php]: Could you explain that `swtich`? It's a bit unclear what is expected here and also what the `case`s means.

**Comment by j0k3r** [comment]
Be careful while removing query parameters.
If you have `site.com?pageid=123` and `site.com?pageid=456` they should be considered as two separate entry and not a single one.

File: src/Wallabag/CoreBundle/Helper/ContentProxy.php (hunk 1 above)
Comment (Kdecherf) [reply src/Wallabag/CoreBundle/Helper/ContentProxy.php]: I'll add a comment to explain this part

**Comment by tcitworld** [comment]
Maybe ignored hosts and patterns should be inside a dedicated file and not hardcoded ?

**Comment by Kdecherf** [comment]
@tcitworld that was my original thought but I decided to go faster by hardcoding it in the first version. @j0k3r are you still okay with that?

**Comment by j0k3r** [comment]
Yeah we agree to hardcode them in 2.3 and to add them in the database in the 2.4 (because we'll need a migration. And also, people will be able to manage them
