### PR TITLE
Fix number of entries in tag/list

### LINKED ISSUE #2006: Number of entries per tag is not correct in tag/list
### Issue details

On tags list, the number of entries per tag is wrong: it's in fact the total entries per tag, but it doesn't take into account the current user. 

We have to use the good query to fetch tags by label and by user.

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #2006 
| License       | MIT

Fix #2006

What kind of tests?

### CODE REVIEW

File: src/Wallabag/CoreBundle/Entity/Tag.php [hunk 1]
```diff
@@ -117,4 +117,16 @@ public function getEntries()
     {
         return $this->entries;
     }
+
+    public function getEntriesByUser($userId)
```
Comment (j0k3r) [inline src/Wallabag/CoreBundle/Entity/Tag.php]: Could this be called `getEntriesByUserId` instead?
