### PR TITLE
Fix assets for subfolder install

### LINKED ISSUE #3485: domain / url problem in 2.3.0
Désolé mais je suis plus à l'aise en français.

Je viens de mettre à jour wallabag : aucune erreur rencontrée lors de la mise à jour mais l'interface est cassée (police non chargée, certains visuels sont inaccessibles etc.).

Je pense que le soucis vient du fait que mon installation n'est pas sur un (sous) domaine dédié : elle est de type http://www.domain.tdl/wallabag

Je pense que c'est en raison de l'ajout d'un paramètre _domain_name_.

wallabag

Au début j'avais mis http://www.domain.tdl mais j'ai aussi essayé en mettant l'url complète (modif dans parameters.yml) : http://www.domain.tdl/wallabag (aucune différence après un php bin/console cache:clear --env=prod)

Je donne un exemple de lien css/média/font inopérant 👍 
https://www.domain.tdl/fonts/MaterialIcons-Regular.ttf ( erreur 404 ) qui devrait être : 
https://www.domain.tdl/wallabag/fonts/MaterialIcons-Regular.ttf 

Sinon un grand merci pour cette version.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.0

### PR DESCRIPTION
**Pull request by Kdecherf**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | -
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| Fixed tickets | #3485 
| License       | MIT

Fixes #3485

### CODE REVIEW

File: app/AppKernel.php [hunk 1]
```diff
@@ -78,6 +78,12 @@ public function registerContainerConfiguration(LoaderInterface $loader)
                        'base_url' => 'http://localhost:8080/',
                    ],
                ]);
+            } else {
```
Comment (nicosomb) [inline app/AppKernel.php]: 👍

**Comment by steiler** [comment]
Fixes the issue for me. Assets are now properly loaded.
Thanks
