### PR TITLE
Fix tags listing

### LINKED ISSUE #1994: not all tags are listed properly
### Issue details

In our /tag/list there are listed maximum 10 tags - even if you have more

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.3
* How did you install wallabag? Via `git clone` or by downloading the package?
* Last wallabag version that did not exhibit the issue (if applicable):
* php version:
* OS:
* type of hosting (shared or dedicated):
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### Steps to reproduce/test case

Please provide necessary steps for reproduction of this issue, or better the
reduced test case (without any external dependencies, if possible).

1. add more than 10 tags and assign at least one article to one of them
2. go to /tag/list
3. for me it is written "there are 14 tags". But the listing after that sentence only contains 10 tags

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #1994 
| License       | MIT

Fix #1994

* Remove unused method in tag repository (I don't know why we used pager for tags)

### CODE REVIEW

File: src/Wallabag/CoreBundle/Repository/TagRepository.php [hunk 1]
```diff
@@ -23,22 +21,6 @@ private function getQbForAllTags($userId)
     }
```
Comment (j0k3r) [inline src/Wallabag/CoreBundle/Repository/TagRepository.php]: You can even remove `getQbForAllTags` since only one method use it now.
