### PR TITLE
TagController: fix duplicated tags when renaming them

### LINKED ISSUE #4216: Renaming a tag removes the relation between tag and entry
### Issue details

I tried the renaming tags feature. The tag is renamed but the relation between tag and entry is removed. 

### Environment

* wallabag version (or git revision) that exhibits the issue: master
* How did you install wallabag? Via `git clone`
* php version: 7.3
* OS: debian 
* type of hosting (shared or dedicated): wallabag.it
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL

You can't reproduce it on wallabag.it because I disabled this feature to avoid bad experience for users.

### PR DESCRIPTION
**Pull request by Kdecherf**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | 
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

The fix relies on a workaround available on TagsAssigner, see the
AssignTagsToEntry() signature for detail.

I replaced the findOneByLabel in the corresponding test to assert that
there is no duplicate.

Fixes #4216

### CODE REVIEW

**Comment by Kdecherf** [comment]
Question @wallabag/core:

If we rename a tag with the same label than another existing tag, should we merge them together or should we keep both?

**Comment by j0k3r** [comment]
We should merge I think

**Comment by Kdecherf** [comment]
@j0k3r changes were made to merge tags when renaming a tag with the same label of an existing tag.

File: src/Wallabag/CoreBundle/Controller/TagController.php [hunk 1]
```diff
@@ -152,27 +152,40 @@ public function renameTagAction(Tag $tag, Request $request)
...
-            );
-            foreach ($entries as $entry) {
-                $this->get('wallabag_core.tags_assigner')->assignTagsToEntry(
-                    $entry,
-                    $form->get('label')->getData()
+            $formLabel = $form->get('label')->getData();
+            $newTag = new Tag();
+            $newTag->setLabel($formLabel);
+
+            if ($newTag->getLabel() !== $tag->getLabel()) {
```
Comment (j0k3r) [inline src/Wallabag/CoreBundle/Controller/TagController.php:159]: I tend to avoid using condition which generate too much code indented below.

Maybe you can move the redirect url definition above that condition, flip the check to have a small part in the `if` and return early:

```php
$redirectUrl = $this->get('wallabag_core.helper.redirect')->to($request->headers->get('referer'), '', true);

if ($newTag->getLabel() === $tag->getLabel()) {
    return $this->redirect($redirectUrl);
}

// whole code about renaming

return $this->redirect($redirectUrl);
```

File: src/Wallabag/CoreBundle/Controller/TagController.php [hunk 2]
```diff
@@ -152,27 +152,40 @@ public function renameTagAction(Tag $tag, Request $request)
...
-                $this->getUser()->getId(),
-                $tag->getId()
-            );
-            foreach ($entries as $entry) {
-                $this->get('wallabag_core.tags_assigner')->assignTagsToEntry(
-                    $entry,
-                    $form->get('label')->getData()
+            $formLabel = $form->get('label')->getData();
+            $newTag = new Tag();
+            $newTag->setLabel($formLabel);
```
Comment (j0k3r) [inline src/Wallabag/CoreBundle/Controller/TagController.php:157]: This will avoid having to use a temporary variable

```suggestion
            $newTag->setLabel($form->get('label')->getData());
```

File: src/Wallabag/CoreBundle/Controller/TagController.php [hunk 3]
```diff
@@ -152,27 +152,40 @@ public function renameTagAction(Tag $tag, Request $request)
...
+                    $this->get('wallabag_core.tags_assigner')->assignTagsToEntry(
+                        $entry,
+                        $newTag->getLabel(),
+                        [$newTag]
+                    );
+                    $entry->removeTag($tag);
+                }
+
+                $em = $this->getDoctrine()->getManager();
+                $em->flush();
```
Comment (j0k3r) [inline src/Wallabag/CoreBundle/Controller/TagController.php:180]: Can this be enough?

```suggestion
                $this->getDoctrine()->getManager()->flush();
```
