### PR TITLE
Fix the deletion of Tags/Entries relation when delete an entry

### LINKED ISSUE #2121: SERIOUS BUG - Tags clears on all articles after deleting article contains tags
### Issue details

When I delete article with tags, this tag clears from all other articles! It deleted also from DB, both from w_tag and from w_entry_tag tables
That behaviour is as in site and also in API.
(I'v just lost tag "programming" :-(  )

### Environment

* wallabag version 2.0.4

### Steps to reproduce/test case

Don't check this with your existing tag...... just with new one.

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #2121 
| License       | MIT

Fix #2121

### CODE REVIEW

File: src/Wallabag/CoreBundle/Controller/EntryController.php [hunk 1]
```diff
@@ -23,10 +23,16 @@ private function updateEntry(Entry $entry)
...
+
             $em = $this->getDoctrine()->getManager();
             $em->persist($entry);
             $em->flush();
         } catch (\Exception $e) {
+            $this->get('logger')->error('Error while saving an entry', [
+                'exception' => $e,
+                'entry' => $entry,
+            ]);
+
```
Comment (nicosomb) [inline src/Wallabag/CoreBundle/Controller/EntryController.php]: :+1:

**Comment by nicosomb** [comment]
It seems to be OK for me.
