### PR TITLE
API return an error with empty quote

### LINKED ISSUE #4137: Can't save an annotation with empty quote
### Issue details

I'm getting `500 Internal Server Error` (self-hosted 2.3.8) when I POST an annotation without `quote` via API. The `quote` is an optional parameter.
The same exact call works ok against `app.wallabag.it`.
I also know that the same call worked alright in the past (when I was writing [wallabag-api-wrapper](https://github.com/di72nn/wallabag-api-wrapper)).

Log:
```
[2019-08-24 09:50:31] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\NotNullConstraintViolationException: "An exception occurred while executing 'INSERT INTO wallabagv2_annotation (text, created_at, updated_at, quote, ranges, user_id, entry_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["Test annotation from API", "2019-08-24 09:50:31", "2019-08-24 09:50:31", null, "a:1:{i:0;a:4:{s:5:\"start\";s:5:\"\/p[1]\";s:11:\"startOffset\";s:1:\"0\";s:3:\"end\";s:5:\"\/p[1]\";s:9:\"endOffset\";s:3:\"100\";}}", 4, 123]:  Column 'quote' cannot be null" at /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO wallabagv2_annotation (text, created_at, updated_at, quote, ranges, user_id, entry_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"Test annotation from API\", \"2019-08-24 09:50:31\", \"2019-08-24 09:50:31\", null, \"a:1:{i:0;a:4:{s:5:\\\"start\\\";s:5:\\\"\\/p[1]\\\";s:11:\\\"startOffset\\\";s:1:\\\"0\\\";s:3:\\\"end\\\";s:5:\\\"\\/p[1]\\\";s:9:\\\"endOffset\\\";s:3:\\\"100\\\";}}\", 4, 123]:\n\nColumn 'quote' cannot be null at /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112, Doctrine\\DBAL\\Driver\\Mysqli\\MysqliException(code: 0): Column 'quote' cannot be null at /usr/share/webapps/wallabag/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:172)"} []
```

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.3.8
* How did you install wallabag? by downloading the package
* Last wallabag version that did not exhibit the issue (if applicable): ?
* php version: 7.3
* OS: Arch
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): MySQL/MariaDB

### PR DESCRIPTION
**Pull request by aaa2000**
Fix #4137

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes/no
| Documentation | no
| Translation   | no
| CHANGELOG.md  | no
| License       | MIT

### CODE REVIEW

File: src/Wallabag/ApiBundle/Controller/AnnotationRestController.php [hunk 1]
```diff
@@ -39,7 +39,7 @@ public function getAnnotationsAction(Entry $entry)
      * @ApiDoc(
      *      requirements={
      *          {"name"="ranges", "dataType"="array", "requirement"="\w+", "description"="The range array for the annotation"},
-     *          {"name"="quote", "dataType"="string", "required"=false, "description"="Optional, quote for the annotation"},
+     *          {"name"="quote", "dataType"="string", "required"=true, "description"="Quote for the annotation"},
```
Comment (j0k3r) [inline src/Wallabag/ApiBundle/Controller/AnnotationRestController.php]: Changing this to required will force all client to update their code.
Maybe we should remind to add it in the changelog as a _small_ BC.

What do you think @wallabag/core?

Comment (tcitworld) [reply src/Wallabag/ApiBundle/Controller/AnnotationRestController.php]: I don't know of any client that supports annotations, apart from https://github.com/di72nn/wallabag-api-wrapper from @di72nn 

Fine by me to add it in the changelog of course.

Comment (tcitworld) [reply src/Wallabag/ApiBundle/Controller/AnnotationRestController.php]: Anyway I'm not even sure what's the purpose of this field.

Comment (di72nn) [reply src/Wallabag/ApiBundle/Controller/AnnotationRestController.php]: So as far as anyone here knows this field has no use (in current implementation), everything works ok if it's `null` (it did work ok previously, it does now if it's nullable in DB) - why not make it nullable?
Otherwise you make effectively useless field mandatory.

Also it is already nullable with wallabag.it (postgres?).

Comment (nicosomb) [reply src/Wallabag/ApiBundle/Controller/AnnotationRestController.php]: > Also it is already nullable with wallabag.it (postgres?).

Not yet postgres

Comment (aaa2000) [reply src/Wallabag/ApiBundle/Controller/AnnotationRestController.php]: The frontend does not seem to use the `quote` text, so the quote is now optionnal. If the quote is empty, an empty string is saved

**Comment by di72nn** [comment]
It will accept `quote == null` or the `quote` parameter being omitted, right?

**Comment by j0k3r** [comment]
@di72nn that's right
