### PR TITLE
Redirect to homepage if referer is null

### LINKED ISSUE #1924: Calling directly /archive/123 gives 500 Internal Server Error
### Issue details

If i call directly the URL (without any referer or the like) in my browser, e.g. https://wallabag.domain.de/archive/832
I get the error message in the browser:

```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

The log file of wallabag says:
```
[2016-04-14 21:36:36] request.INFO: Matched route "archive_entry". {"route_parameters":{"_controller":"Wallabag\\CoreBundle\\Controller\\EntryController::toggleArchiveAction","id":"832","_route":"archive_entry"},"request_uri":"https://wallabag.domain.de/archive/832"} []
[2016-04-14 21:36:36] security.DEBUG: Read existing security token from the session. {"key":"_security_secured_area"} []
[2016-04-14 21:36:36] security.DEBUG: User was reloaded from a user provider. {"username":"strubbl","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2016-04-14 21:36:37] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Cannot redirect to an empty URL." at /home/strubbl/git/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/RedirectResponse.php line 76 {"exception":"[object] (InvalidArgumentException(code: 0): Cannot redirect to an empty URL. at /home/strubbl/git/wallabag/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/RedirectResponse.php:76)"} []
[2016-04-14 21:36:37] security.DEBUG: Stored the security token in the session. {"key":"_security_secured_area"} []
```

In the end, my article indeed gets archived, but i see this error message. Same with star and delete (and maybe some other function i don't know of).

PS: I found this bug during Android app development, because the app directly calls this URL and compares the response code to 200.

### Environment

* wallabag version (or git revision) that exhibits the issue: 2.0.0
* How did you install wallabag? Via `git clone`
* Last wallabag version that did not exhibit the issue (if applicable): - 
* php version: PHP 5.6.19-0+deb8u1
* OS: Debian
* type of hosting (shared or dedicated): dedicated
* which storage system you choose at install (SQLite, MySQL/MariaDB or PostgreSQL): mysql

### Steps to reproduce/test case

1. open browser
2. enter url https://wallabag.domain.de/archive/832 (with valid article id of course)

### PR DESCRIPTION
**Pull request by nicosomb**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Documentation | no
| Translation   | no
| Fixed tickets | #1924
| License       | MIT

Fix #1924

### CODE REVIEW

File: src/Wallabag/CoreBundle/Tests/Helper/RedirectTest.php [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+        $redirectUrl = $this->redirect->to(null, 'fallback');
+
+        $this->assertEquals('fallback', $redirectUrl);
+    }
+
+    public function testRedirectToNullWithoutFallback()
+    {
+        $redirectUrl = $this->redirect->to(null);
+
+        $this->assertEquals($this->routerMock->generate('homepage'), $redirectUrl);
```
Comment (nicosomb) [inline src/Wallabag/CoreBundle/Tests/Helper/RedirectTest.php]: I have a doubt about this test because `$this->routerMock->generate('homepage')`. Is that normal?

File: src/Wallabag/CoreBundle/Helper/Redirect.php [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+     */
+    public function to($url, $fallback = '')
+    {
+        $returnUrl = $url;
+
+        if (null === $url) {
+            if ('' !== $fallback) {
+                $returnUrl = $fallback;
+            } else {
+                $returnUrl = $this->router->generate('homepage');
```
Comment (j0k3r) [inline src/Wallabag/CoreBundle/Helper/Redirect.php]: I would rather do:

```php
if (null !== $url) {
    return $url;
}

if ('' === $fallback) {
    return $this->router->generate('homepage');
}

return $fallback;
```

Also, don't forget to add a description of this helper class (before the class definition)

File: src/Wallabag/CoreBundle/Tests/Helper/RedirectTest.php (hunk 1 above)
Comment (j0k3r) [inline src/Wallabag/CoreBundle/Tests/Helper/RedirectTest.php]: Because you need to define an expect method in your mock, like:

```php
$router->expects($this->once())
    ->method('generate')
    ->with('homepage')
    ->willReturn('/homepage');
```

File: src/Wallabag/CoreBundle/Tests/Helper/RedirectTest.php [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+    {
+        $redirectUrl = $this->redirect->to('/unread/list');
+
+        $this->assertEquals('/unread/list', $redirectUrl);
+    }
+
+    private function getRouterMock()
+    {
+        $mock = $this->getMockBuilder('Symfony\Component\Routing\Router')
+            ->disableOriginalConstructor()
```
Comment (FabienM) [inline src/Wallabag/CoreBundle/Tests/Helper/RedirectTest.php]: Why ?

File: src/Wallabag/CoreBundle/Controller/EntryController.php [hunk 4]
```diff
@@ -408,7 +412,11 @@ public function deleteEntryAction(Request $request, Entry $entry)
         );
 
         // don't redirect user to the deleted entry
-        return $this->redirect($url !== $request->headers->get('referer') ? $request->headers->get('referer') : $this->generateUrl('homepage'));
+        $to = ($url !== $request->headers->get('referer') ? $request->headers->get('referer') : $this->generateUrl('homepage'));
```
Comment (FabienM) [inline src/Wallabag/CoreBundle/Controller/EntryController.php]: Isn't the homepage fallback thing handled by the service ?
